language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "pypy"
env:
    - DJANGO="django>=1.5,<1.6"
    - DJANGO="django>=1.6,<1.7"
    - DJANGO="https://www.djangoproject.com/download/1.7c1/tarball/"
install:
    - "pip install user-agents"
    - "pip install ${DJANGO}"
script:
    - "python manage.py test"
